---
- name: Install Nginx
  hosts: all
  remote_user: keskus
  become: yes
  
  roles:
    - nginx
#  vars:
#    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
