---
- name: Deploy Nginx
  hosts: nginx_servers
  remote_user: ansible
  become: yes

  roles:
    - nginx

  handlers:
    - name: Start Nginx
      service:
        name: nginx
        state: started

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted